services:
  main_app:
    build: .
    command: sh -c "npx prisma migrate deploy && npm run start"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://${usermysql}:${passwordmysql}@db:3306/auctify
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - AUTH_TRUST_HOST=1
    networks:
      - auctify_net
    depends_on:
      db:
        condition: service_healthy
  db:
    image: docker.io/library/mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${passwordmysqlroot}
      - MYSQL_DATABASE=auctify
      - MYSQL_PASSWORD=${passwordmysql}
      - MYSQL_USER=${usermysql}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - auctify_net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  auctify_net:
volumes:
  mysqldata:
